# Generated by Django 4.2 on 2025-06-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimony_photos/'),
        ),
    ]
